tasks:
- install.upgrade:
    client.0:
- print: "**** done install.upgrade on client.0"
- ceph-fuse:
    client.0:
      mounted: false
- ceph-fuse:
    client.0:
- print: "**** done remount client"
