overrides:
  ceph:
    log-whitelist:
      - not responding, replacing
      - \(MDS_INSUFFICIENT_STANDBY\)
      - \(MDS_ALL_DOWN\)
      - \(MDS_UP_LESS_THAN_MAX\)
tasks:
  - cephfs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.cephfs.test_failover
