tasks:
- ceph-fuse:
- print: "**** done luminous client"
- exec:
    mon.a:
    - ceph fs set cephfs allow_new_snaps true --yes-i-really-mean-it
- workunit:
    timeout: 5m
    cleanup: false
    clients:
      client.0:
      - fs/snap-hierarchy.sh
- print: "**** done snap hierarchy"
