tasks:
- exec:
    mon.a:
    - ceph status
    - ceph fs dump --format=json-pretty
    - ceph fs set cephfs max_mds 2 && exit 1 || true
- print: "**** confirmed cannot set max_mds=2"
- exec:
    mon.a:
    - ceph fs set cephfs allow_new_snaps true
