overrides:
  ceph:
    log-whitelist:
      - bad backtrace on inode
tasks:
- cephfs_upgrade_snap:
- print: "**** upgraded snapshot metadata"
- exec:
    mon.a:
    - ceph fs set cephfs max_mds 2
- print: "**** increased max_mds=2"
- sleep:
    duration: 10
- exec:
    mon.a:
    - ceph fs dump | grep '^max_mds.*2'
